# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CgoExample < Formula
  desc "Example binary distribution using homebrew."
  homepage "https://github.com/regel/homebrew-cgo-example"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/regel/cgo-example/releases/download/v0.0.4/cgo-example_Darwin_x86_64.tar.gz"
      sha256 "e548df0ff31e06fee6774a569c543107f579624ddfa4896711cc71172ef428f2"

      def install
        bin.install "cgo-example"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/regel/cgo-example/releases/download/v0.0.4/cgo-example_Darwin_arm64.tar.gz"
      sha256 "fd4c69a7e7ca6b40bf5beab4581c148ef5b596933f3569ef55e0592e8982ffa5"

      def install
        bin.install "cgo-example"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/regel/cgo-example/releases/download/v0.0.4/cgo-example_Linux_x86_64.tar.gz"
      sha256 "6b87c2d9e10623c596f368882db49ad673f74bdce659a69a408840fe3481d0a8"

      def install
        bin.install "cgo-example"
      end
    end
  end
end
